methods = {
	'visualization': ['Data Visualization', {
		'bar-chart': 'Bar Chart',
		'pie-chart': 'Pie Chart',
		// 'line-chart': 'Line Chart',
		// 'area-chart': 'Area Chart',
		'boxplot': 'Box Plot',
		'histogram': 'Histogram',
		'areaspline': 'Area Spline Chart',
		'scatter': 'Scatter Plot',
		'3d-scatter': '3D Scatter Plot',
		'qqplot': 'Q-Q Plot',
		'heat-map': 'Heat Map',
		// 'treemap': 'Treemap',
		// 'radar-chart': 'Radar Chart',
		'packed-bubble-chart': 'Packed Bubble Chart',
		'sunburst': 'Sunburst',
		// 'network-graph': 'Network Graph',
		// 'range-series': 'Range Series',
		// 'stream-graph': 'Stream Graph',
		// 'word-cloud': 'Word Cloud',
		// 'sankey-diagram': 'Sankey Diagram',
		// 'bullet-chart': 'Bullet Chart',
		'parallel-coordinates-chart': 'Parallel Coordinates Chart',
		// 'venn-diagram': 'Venn Diagram',
		// 'waterfall-chart': 'Waterfall Chart',
	}],
	'descriptive': ['Descriptive Analysis', {
		'summary': 'Summary',
		'pearson-correlation': 'Pearson Correlation',
		'spearman-correlation': 'Spearman\'s Rank Correlation',
		// 'phi': 'Phi Correlation',
	}],
	'compare': ['Compare Means or Variances', {
		'one-sample-t-test': 'One-Sample T Test',
		// 'independent-samples-t-test': 'Independent-Sample T Test',
		// 'paired-samples-t-test': 'Paired-Sample T Test',
		'anova': 'One-Way ANOVA',
		'f-test': 'F Test',
		// 'bartlett': 'Bartlett\'s Test',
	}],
	'causal': ['Causal Analysis', {
		'regression': 'Linear Regression',
		// 'regression-logistic': 'Binary Logistic Regression',
		// 'mca': 'Multiple Classification Analysis',
	}],
	// 'nonparametric': ['Nonparametric', {
		// 'lilliefors': 'Lilliefors Test',
		// 'chisquare': 'Chi-Square Test of Independence',
		// 'runs': 'Runs Test',
	// }],
	'multivariate': ['Multivariate', {
		'qqplot-multivariate': 'Multivariate Normal Q-Q Plot',
		// 'mardia-test': 'Mardia\'s Test',
		// 'manova': 'MANOVA',
		// 'biplot': 'Biplot',
		// 'pca': 'Principal Component Analysis',
	}],
	// 'timeseries': ['Time Series', {
		// 'semi-average': 'Semi-Average',
		// 'least-square': 'Linear Least Square',
	// }],
	'others': ['Others', {
		'custom-script': 'Custom Script',
	}],
}
